# Generated by Django 6.0.3 on 2026-03-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_faculty_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("contact", "İletişim Bilgileri"),
                            ("navigation", "Ana Menü / Navigasyon"),
                            ("general", "Genel Bilgi"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "Üniversite Bilgisi",
                "verbose_name_plural": "Üniversite Bilgileri",
                "unique_together": {("category", "key")},
            },
        ),
    ]
