# Generated by Django 6.0.3 on 2026-03-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='course_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='department_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='universityinfo',
            name='universityinfo_search_idx',
        ),
    ]
